#ifndef TOUCH_H
#define TOUCH_H


#include "Main.h"

#define TOUCH_GPIO_INIT			GPIOA->MODER |= GPIO_MODER_MODER12_0;\
								GPIOC->ODR &= ~(GPIO_ODR_6|GPIO_ODR_7|GPIO_ODR_8|GPIO_ODR_9)
				

#define TOUCH_RELEASE_CHARGE  	GPIOC->MODER &= ~(GPIO_MODER_MODER6_1|GPIO_MODER_MODER7_1|GPIO_MODER_MODER8_1|GPIO_MODER_MODER9_1);\
								GPIOC->MODER |= (GPIO_MODER_MODER6_0|GPIO_MODER_MODER7_0|GPIO_MODER_MODER8_0|GPIO_MODER_MODER9_0)
			
#define TOUCH_RECHARGE_CHARGE 	GPIOC->MODER &= ~(GPIO_MODER_MODER6_0|GPIO_MODER_MODER7_0|GPIO_MODER_MODER8_0|GPIO_MODER_MODER9_0);\
								GPIOC->MODER |= (GPIO_MODER_MODER6_1|GPIO_MODER_MODER7_1|GPIO_MODER_MODER8_1|GPIO_MODER_MODER9_1)
								
#define	 TOUCH_COM_SET			GPIOA->ODR |= GPIO_ODR_12;
#define	 TOUCH_COM_CLR			GPIOA->ODR &= ~GPIO_ODR_12;


#define TOUCH_DELAY_1us 		Delay_us(1)

void Touch_Init(void);

#endif
